// Generated by https://quicktype.io
export interface Leagues {
  leagues: League[];
}

export interface League {
  idLeague: string;
  strLeague: string;
  strSport: StrSport;
  strLeagueAlternate: string;
}

export enum StrSport {
  AmericanFootball = "American Football",
  Basketball = "Basketball",
  IceHockey = "Ice Hockey",
  Motorsport = "Motorsport",
  Soccer = "Soccer",
}
